// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalculatingRoute.proto

package CalculatingRoute;

public interface addressDistanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CalculatingRoute.addressDistance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *sistema devolve a distacia ate o destino
   * </pre>
   *
   * <code>int32 destination_km = 1;</code>
   */
  int getDestinationKm();
}
