// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalculatingRoute.proto

package CalculatingRoute;

/**
 * <pre>
 * RPC return Method 3
 * </pre>
 *
 * Protobuf type {@code CalculatingRoute.addressDistance}
 */
public  final class addressDistance extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CalculatingRoute.addressDistance)
    addressDistanceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use addressDistance.newBuilder() to construct.
  private addressDistance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private addressDistance() {
    destinationKm_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private addressDistance(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            destinationKm_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_addressDistance_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_addressDistance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CalculatingRoute.addressDistance.class, CalculatingRoute.addressDistance.Builder.class);
  }

  public static final int DESTINATION_KM_FIELD_NUMBER = 1;
  private int destinationKm_;
  /**
   * <pre>
   *sistema devolve a distacia ate o destino
   * </pre>
   *
   * <code>int32 destination_km = 1;</code>
   */
  public int getDestinationKm() {
    return destinationKm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (destinationKm_ != 0) {
      output.writeInt32(1, destinationKm_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (destinationKm_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, destinationKm_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CalculatingRoute.addressDistance)) {
      return super.equals(obj);
    }
    CalculatingRoute.addressDistance other = (CalculatingRoute.addressDistance) obj;

    boolean result = true;
    result = result && (getDestinationKm()
        == other.getDestinationKm());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DESTINATION_KM_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationKm();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CalculatingRoute.addressDistance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.addressDistance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.addressDistance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.addressDistance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.addressDistance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.addressDistance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.addressDistance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CalculatingRoute.addressDistance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CalculatingRoute.addressDistance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CalculatingRoute.addressDistance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CalculatingRoute.addressDistance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CalculatingRoute.addressDistance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CalculatingRoute.addressDistance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RPC return Method 3
   * </pre>
   *
   * Protobuf type {@code CalculatingRoute.addressDistance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CalculatingRoute.addressDistance)
      CalculatingRoute.addressDistanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_addressDistance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_addressDistance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalculatingRoute.addressDistance.class, CalculatingRoute.addressDistance.Builder.class);
    }

    // Construct using CalculatingRoute.addressDistance.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      destinationKm_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_addressDistance_descriptor;
    }

    @java.lang.Override
    public CalculatingRoute.addressDistance getDefaultInstanceForType() {
      return CalculatingRoute.addressDistance.getDefaultInstance();
    }

    @java.lang.Override
    public CalculatingRoute.addressDistance build() {
      CalculatingRoute.addressDistance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CalculatingRoute.addressDistance buildPartial() {
      CalculatingRoute.addressDistance result = new CalculatingRoute.addressDistance(this);
      result.destinationKm_ = destinationKm_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CalculatingRoute.addressDistance) {
        return mergeFrom((CalculatingRoute.addressDistance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CalculatingRoute.addressDistance other) {
      if (other == CalculatingRoute.addressDistance.getDefaultInstance()) return this;
      if (other.getDestinationKm() != 0) {
        setDestinationKm(other.getDestinationKm());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CalculatingRoute.addressDistance parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CalculatingRoute.addressDistance) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int destinationKm_ ;
    /**
     * <pre>
     *sistema devolve a distacia ate o destino
     * </pre>
     *
     * <code>int32 destination_km = 1;</code>
     */
    public int getDestinationKm() {
      return destinationKm_;
    }
    /**
     * <pre>
     *sistema devolve a distacia ate o destino
     * </pre>
     *
     * <code>int32 destination_km = 1;</code>
     */
    public Builder setDestinationKm(int value) {
      
      destinationKm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *sistema devolve a distacia ate o destino
     * </pre>
     *
     * <code>int32 destination_km = 1;</code>
     */
    public Builder clearDestinationKm() {
      
      destinationKm_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CalculatingRoute.addressDistance)
  }

  // @@protoc_insertion_point(class_scope:CalculatingRoute.addressDistance)
  private static final CalculatingRoute.addressDistance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CalculatingRoute.addressDistance();
  }

  public static CalculatingRoute.addressDistance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<addressDistance>
      PARSER = new com.google.protobuf.AbstractParser<addressDistance>() {
    @java.lang.Override
    public addressDistance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new addressDistance(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<addressDistance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<addressDistance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CalculatingRoute.addressDistance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

