// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalculatingRoute.proto

package CalculatingRoute;

/**
 * <pre>
 * RPC return Method 1
 * </pre>
 *
 * Protobuf type {@code CalculatingRoute.lookingAddress}
 */
public  final class lookingAddress extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CalculatingRoute.lookingAddress)
    lookingAddressOrBuilder {
private static final long serialVersionUID = 0L;
  // Use lookingAddress.newBuilder() to construct.
  private lookingAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private lookingAddress() {
    lookingAddress_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private lookingAddress(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            lookingAddress_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_lookingAddress_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_lookingAddress_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CalculatingRoute.lookingAddress.class, CalculatingRoute.lookingAddress.Builder.class);
  }

  public static final int LOOKING_ADDRESS_FIELD_NUMBER = 1;
  private volatile java.lang.Object lookingAddress_;
  /**
   * <pre>
   *sistema entendera que a string representa a procura do endereco
   * </pre>
   *
   * <code>string looking_address = 1;</code>
   */
  public java.lang.String getLookingAddress() {
    java.lang.Object ref = lookingAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lookingAddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *sistema entendera que a string representa a procura do endereco
   * </pre>
   *
   * <code>string looking_address = 1;</code>
   */
  public com.google.protobuf.ByteString
      getLookingAddressBytes() {
    java.lang.Object ref = lookingAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lookingAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLookingAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, lookingAddress_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLookingAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, lookingAddress_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CalculatingRoute.lookingAddress)) {
      return super.equals(obj);
    }
    CalculatingRoute.lookingAddress other = (CalculatingRoute.lookingAddress) obj;

    boolean result = true;
    result = result && getLookingAddress()
        .equals(other.getLookingAddress());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOOKING_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getLookingAddress().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CalculatingRoute.lookingAddress parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.lookingAddress parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.lookingAddress parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.lookingAddress parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.lookingAddress parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.lookingAddress parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.lookingAddress parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CalculatingRoute.lookingAddress parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CalculatingRoute.lookingAddress parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CalculatingRoute.lookingAddress parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CalculatingRoute.lookingAddress parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CalculatingRoute.lookingAddress parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CalculatingRoute.lookingAddress prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RPC return Method 1
   * </pre>
   *
   * Protobuf type {@code CalculatingRoute.lookingAddress}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CalculatingRoute.lookingAddress)
      CalculatingRoute.lookingAddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_lookingAddress_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_lookingAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalculatingRoute.lookingAddress.class, CalculatingRoute.lookingAddress.Builder.class);
    }

    // Construct using CalculatingRoute.lookingAddress.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lookingAddress_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_lookingAddress_descriptor;
    }

    @java.lang.Override
    public CalculatingRoute.lookingAddress getDefaultInstanceForType() {
      return CalculatingRoute.lookingAddress.getDefaultInstance();
    }

    @java.lang.Override
    public CalculatingRoute.lookingAddress build() {
      CalculatingRoute.lookingAddress result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CalculatingRoute.lookingAddress buildPartial() {
      CalculatingRoute.lookingAddress result = new CalculatingRoute.lookingAddress(this);
      result.lookingAddress_ = lookingAddress_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CalculatingRoute.lookingAddress) {
        return mergeFrom((CalculatingRoute.lookingAddress)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CalculatingRoute.lookingAddress other) {
      if (other == CalculatingRoute.lookingAddress.getDefaultInstance()) return this;
      if (!other.getLookingAddress().isEmpty()) {
        lookingAddress_ = other.lookingAddress_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CalculatingRoute.lookingAddress parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CalculatingRoute.lookingAddress) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object lookingAddress_ = "";
    /**
     * <pre>
     *sistema entendera que a string representa a procura do endereco
     * </pre>
     *
     * <code>string looking_address = 1;</code>
     */
    public java.lang.String getLookingAddress() {
      java.lang.Object ref = lookingAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lookingAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *sistema entendera que a string representa a procura do endereco
     * </pre>
     *
     * <code>string looking_address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLookingAddressBytes() {
      java.lang.Object ref = lookingAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lookingAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *sistema entendera que a string representa a procura do endereco
     * </pre>
     *
     * <code>string looking_address = 1;</code>
     */
    public Builder setLookingAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lookingAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *sistema entendera que a string representa a procura do endereco
     * </pre>
     *
     * <code>string looking_address = 1;</code>
     */
    public Builder clearLookingAddress() {
      
      lookingAddress_ = getDefaultInstance().getLookingAddress();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *sistema entendera que a string representa a procura do endereco
     * </pre>
     *
     * <code>string looking_address = 1;</code>
     */
    public Builder setLookingAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lookingAddress_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CalculatingRoute.lookingAddress)
  }

  // @@protoc_insertion_point(class_scope:CalculatingRoute.lookingAddress)
  private static final CalculatingRoute.lookingAddress DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CalculatingRoute.lookingAddress();
  }

  public static CalculatingRoute.lookingAddress getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<lookingAddress>
      PARSER = new com.google.protobuf.AbstractParser<lookingAddress>() {
    @java.lang.Override
    public lookingAddress parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new lookingAddress(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<lookingAddress> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<lookingAddress> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CalculatingRoute.lookingAddress getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

