// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalculatingRoute.proto

package CalculatingRoute;

public interface lookingAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CalculatingRoute.lookingAddress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *sistema entendera que a string representa a procura do endereco
   * </pre>
   *
   * <code>string looking_address = 1;</code>
   */
  java.lang.String getLookingAddress();
  /**
   * <pre>
   *sistema entendera que a string representa a procura do endereco
   * </pre>
   *
   * <code>string looking_address = 1;</code>
   */
  com.google.protobuf.ByteString
      getLookingAddressBytes();
}
