// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalculatingRoute.proto

package CalculatingRoute;

/**
 * <pre>
 * RPC message Method 1 and Method 3
 * </pre>
 *
 * Protobuf type {@code CalculatingRoute.requestAddress}
 */
public  final class requestAddress extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CalculatingRoute.requestAddress)
    requestAddressOrBuilder {
private static final long serialVersionUID = 0L;
  // Use requestAddress.newBuilder() to construct.
  private requestAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private requestAddress() {
    stringAddress_ = "";
    zIPCode_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private requestAddress(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            stringAddress_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            zIPCode_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_requestAddress_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_requestAddress_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CalculatingRoute.requestAddress.class, CalculatingRoute.requestAddress.Builder.class);
  }

  public static final int STRINGADDRESS_FIELD_NUMBER = 1;
  private volatile java.lang.Object stringAddress_;
  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string stringAddress = 1;</code>
   */
  public java.lang.String getStringAddress() {
    java.lang.Object ref = stringAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stringAddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string stringAddress = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStringAddressBytes() {
    java.lang.Object ref = stringAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stringAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ZIPCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object zIPCode_;
  /**
   * <pre>
   *client digita zipcode
   * </pre>
   *
   * <code>string ZIPCode = 2;</code>
   */
  public java.lang.String getZIPCode() {
    java.lang.Object ref = zIPCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      zIPCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *client digita zipcode
   * </pre>
   *
   * <code>string ZIPCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getZIPCodeBytes() {
    java.lang.Object ref = zIPCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      zIPCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStringAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stringAddress_);
    }
    if (!getZIPCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, zIPCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStringAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stringAddress_);
    }
    if (!getZIPCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, zIPCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CalculatingRoute.requestAddress)) {
      return super.equals(obj);
    }
    CalculatingRoute.requestAddress other = (CalculatingRoute.requestAddress) obj;

    boolean result = true;
    result = result && getStringAddress()
        .equals(other.getStringAddress());
    result = result && getZIPCode()
        .equals(other.getZIPCode());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STRINGADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getStringAddress().hashCode();
    hash = (37 * hash) + ZIPCODE_FIELD_NUMBER;
    hash = (53 * hash) + getZIPCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CalculatingRoute.requestAddress parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.requestAddress parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.requestAddress parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.requestAddress parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.requestAddress parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CalculatingRoute.requestAddress parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CalculatingRoute.requestAddress parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CalculatingRoute.requestAddress parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CalculatingRoute.requestAddress parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CalculatingRoute.requestAddress parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CalculatingRoute.requestAddress parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CalculatingRoute.requestAddress parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CalculatingRoute.requestAddress prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RPC message Method 1 and Method 3
   * </pre>
   *
   * Protobuf type {@code CalculatingRoute.requestAddress}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CalculatingRoute.requestAddress)
      CalculatingRoute.requestAddressOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_requestAddress_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_requestAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalculatingRoute.requestAddress.class, CalculatingRoute.requestAddress.Builder.class);
    }

    // Construct using CalculatingRoute.requestAddress.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      stringAddress_ = "";

      zIPCode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CalculatingRoute.CalculatingRouteImpl.internal_static_CalculatingRoute_requestAddress_descriptor;
    }

    @java.lang.Override
    public CalculatingRoute.requestAddress getDefaultInstanceForType() {
      return CalculatingRoute.requestAddress.getDefaultInstance();
    }

    @java.lang.Override
    public CalculatingRoute.requestAddress build() {
      CalculatingRoute.requestAddress result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CalculatingRoute.requestAddress buildPartial() {
      CalculatingRoute.requestAddress result = new CalculatingRoute.requestAddress(this);
      result.stringAddress_ = stringAddress_;
      result.zIPCode_ = zIPCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CalculatingRoute.requestAddress) {
        return mergeFrom((CalculatingRoute.requestAddress)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CalculatingRoute.requestAddress other) {
      if (other == CalculatingRoute.requestAddress.getDefaultInstance()) return this;
      if (!other.getStringAddress().isEmpty()) {
        stringAddress_ = other.stringAddress_;
        onChanged();
      }
      if (!other.getZIPCode().isEmpty()) {
        zIPCode_ = other.zIPCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CalculatingRoute.requestAddress parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CalculatingRoute.requestAddress) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object stringAddress_ = "";
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string stringAddress = 1;</code>
     */
    public java.lang.String getStringAddress() {
      java.lang.Object ref = stringAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string stringAddress = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringAddressBytes() {
      java.lang.Object ref = stringAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string stringAddress = 1;</code>
     */
    public Builder setStringAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stringAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string stringAddress = 1;</code>
     */
    public Builder clearStringAddress() {
      
      stringAddress_ = getDefaultInstance().getStringAddress();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string stringAddress = 1;</code>
     */
    public Builder setStringAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stringAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object zIPCode_ = "";
    /**
     * <pre>
     *client digita zipcode
     * </pre>
     *
     * <code>string ZIPCode = 2;</code>
     */
    public java.lang.String getZIPCode() {
      java.lang.Object ref = zIPCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zIPCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *client digita zipcode
     * </pre>
     *
     * <code>string ZIPCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getZIPCodeBytes() {
      java.lang.Object ref = zIPCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zIPCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *client digita zipcode
     * </pre>
     *
     * <code>string ZIPCode = 2;</code>
     */
    public Builder setZIPCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      zIPCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *client digita zipcode
     * </pre>
     *
     * <code>string ZIPCode = 2;</code>
     */
    public Builder clearZIPCode() {
      
      zIPCode_ = getDefaultInstance().getZIPCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *client digita zipcode
     * </pre>
     *
     * <code>string ZIPCode = 2;</code>
     */
    public Builder setZIPCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      zIPCode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CalculatingRoute.requestAddress)
  }

  // @@protoc_insertion_point(class_scope:CalculatingRoute.requestAddress)
  private static final CalculatingRoute.requestAddress DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CalculatingRoute.requestAddress();
  }

  public static CalculatingRoute.requestAddress getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<requestAddress>
      PARSER = new com.google.protobuf.AbstractParser<requestAddress>() {
    @java.lang.Override
    public requestAddress parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new requestAddress(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<requestAddress> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<requestAddress> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CalculatingRoute.requestAddress getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

