// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalculatingRoute.proto

package CalculatingRoute;

public interface requestAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CalculatingRoute.requestAddress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string stringAddress = 1;</code>
   */
  java.lang.String getStringAddress();
  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string stringAddress = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringAddressBytes();

  /**
   * <pre>
   *client digita zipcode
   * </pre>
   *
   * <code>string ZIPCode = 2;</code>
   */
  java.lang.String getZIPCode();
  /**
   * <pre>
   *client digita zipcode
   * </pre>
   *
   * <code>string ZIPCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getZIPCodeBytes();
}
