// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPublicStatus.proto

package TransportPublicStatus;

public interface transpSelectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransportPublicStatus.transpSelection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *variaveis da mensagem
   * </pre>
   *
   * <code>string transportOption = 1;</code>
   */
  java.lang.String getTransportOption();
  /**
   * <pre>
   *variaveis da mensagem
   * </pre>
   *
   * <code>string transportOption = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransportOptionBytes();
}
