// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPublicStatus.proto

package TransportPublicStatus;

public interface transpStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransportPublicStatus.transpStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string transportSituation = 1;</code>
   */
  java.lang.String getTransportSituation();
  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string transportSituation = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransportSituationBytes();
}
