// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPublicStatus.proto

package TransportPublicStatus;

public interface transpSelectedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransportPublicStatus.transpSelected)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *sistema entendera que a string representa a procura do endereco
   * </pre>
   *
   * <code>string transportInformations = 1;</code>
   */
  java.lang.String getTransportInformations();
  /**
   * <pre>
   *sistema entendera que a string representa a procura do endereco
   * </pre>
   *
   * <code>string transportInformations = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransportInformationsBytes();
}
