// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPublicStatus.proto

package TransportPublicStatus;

public interface transResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransportPublicStatus.transResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *sistema devolve a distacia ate o destino
   * </pre>
   *
   * <code>string stringTransResponse = 1;</code>
   */
  java.lang.String getStringTransResponse();
  /**
   * <pre>
   *sistema devolve a distacia ate o destino
   * </pre>
   *
   * <code>string stringTransResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringTransResponseBytes();
}
