// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportPublicStatus.proto

package TransportPublicStatus;

/**
 * <pre>
 * RPC message Method 1
 * </pre>
 *
 * Protobuf type {@code TransportPublicStatus.transpSelection}
 */
public  final class transpSelection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TransportPublicStatus.transpSelection)
    transpSelectionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use transpSelection.newBuilder() to construct.
  private transpSelection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private transpSelection() {
    transportOption_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private transpSelection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            transportOption_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TransportPublicStatus.TransportPublicStatusImpl.internal_static_TransportPublicStatus_transpSelection_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TransportPublicStatus.TransportPublicStatusImpl.internal_static_TransportPublicStatus_transpSelection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TransportPublicStatus.transpSelection.class, TransportPublicStatus.transpSelection.Builder.class);
  }

  public static final int TRANSPORTOPTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object transportOption_;
  /**
   * <pre>
   *variaveis da mensagem
   * </pre>
   *
   * <code>string transportOption = 1;</code>
   */
  public java.lang.String getTransportOption() {
    java.lang.Object ref = transportOption_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transportOption_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *variaveis da mensagem
   * </pre>
   *
   * <code>string transportOption = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTransportOptionBytes() {
    java.lang.Object ref = transportOption_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transportOption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTransportOptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transportOption_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTransportOptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transportOption_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TransportPublicStatus.transpSelection)) {
      return super.equals(obj);
    }
    TransportPublicStatus.transpSelection other = (TransportPublicStatus.transpSelection) obj;

    boolean result = true;
    result = result && getTransportOption()
        .equals(other.getTransportOption());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSPORTOPTION_FIELD_NUMBER;
    hash = (53 * hash) + getTransportOption().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TransportPublicStatus.transpSelection parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TransportPublicStatus.transpSelection parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TransportPublicStatus.transpSelection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TransportPublicStatus.transpSelection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TransportPublicStatus.transpSelection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TransportPublicStatus.transpSelection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TransportPublicStatus.transpSelection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TransportPublicStatus.transpSelection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TransportPublicStatus.transpSelection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TransportPublicStatus.transpSelection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TransportPublicStatus.transpSelection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TransportPublicStatus.transpSelection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TransportPublicStatus.transpSelection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RPC message Method 1
   * </pre>
   *
   * Protobuf type {@code TransportPublicStatus.transpSelection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TransportPublicStatus.transpSelection)
      TransportPublicStatus.transpSelectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransportPublicStatus.TransportPublicStatusImpl.internal_static_TransportPublicStatus_transpSelection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransportPublicStatus.TransportPublicStatusImpl.internal_static_TransportPublicStatus_transpSelection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TransportPublicStatus.transpSelection.class, TransportPublicStatus.transpSelection.Builder.class);
    }

    // Construct using TransportPublicStatus.transpSelection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      transportOption_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TransportPublicStatus.TransportPublicStatusImpl.internal_static_TransportPublicStatus_transpSelection_descriptor;
    }

    @java.lang.Override
    public TransportPublicStatus.transpSelection getDefaultInstanceForType() {
      return TransportPublicStatus.transpSelection.getDefaultInstance();
    }

    @java.lang.Override
    public TransportPublicStatus.transpSelection build() {
      TransportPublicStatus.transpSelection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public TransportPublicStatus.transpSelection buildPartial() {
      TransportPublicStatus.transpSelection result = new TransportPublicStatus.transpSelection(this);
      result.transportOption_ = transportOption_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TransportPublicStatus.transpSelection) {
        return mergeFrom((TransportPublicStatus.transpSelection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TransportPublicStatus.transpSelection other) {
      if (other == TransportPublicStatus.transpSelection.getDefaultInstance()) return this;
      if (!other.getTransportOption().isEmpty()) {
        transportOption_ = other.transportOption_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TransportPublicStatus.transpSelection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TransportPublicStatus.transpSelection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object transportOption_ = "";
    /**
     * <pre>
     *variaveis da mensagem
     * </pre>
     *
     * <code>string transportOption = 1;</code>
     */
    public java.lang.String getTransportOption() {
      java.lang.Object ref = transportOption_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transportOption_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *variaveis da mensagem
     * </pre>
     *
     * <code>string transportOption = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTransportOptionBytes() {
      java.lang.Object ref = transportOption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transportOption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *variaveis da mensagem
     * </pre>
     *
     * <code>string transportOption = 1;</code>
     */
    public Builder setTransportOption(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transportOption_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *variaveis da mensagem
     * </pre>
     *
     * <code>string transportOption = 1;</code>
     */
    public Builder clearTransportOption() {
      
      transportOption_ = getDefaultInstance().getTransportOption();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *variaveis da mensagem
     * </pre>
     *
     * <code>string transportOption = 1;</code>
     */
    public Builder setTransportOptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transportOption_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TransportPublicStatus.transpSelection)
  }

  // @@protoc_insertion_point(class_scope:TransportPublicStatus.transpSelection)
  private static final TransportPublicStatus.transpSelection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TransportPublicStatus.transpSelection();
  }

  public static TransportPublicStatus.transpSelection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<transpSelection>
      PARSER = new com.google.protobuf.AbstractParser<transpSelection>() {
    @java.lang.Override
    public transpSelection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new transpSelection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<transpSelection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<transpSelection> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public TransportPublicStatus.transpSelection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

