// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteSelection.proto

package RouteSelection;

/**
 * <pre>
 * RPC message Method 2
 * </pre>
 *
 * Protobuf type {@code RouteSelection.requestTransport}
 */
public  final class requestTransport extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RouteSelection.requestTransport)
    requestTransportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use requestTransport.newBuilder() to construct.
  private requestTransport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private requestTransport() {
    reqTransport_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private requestTransport(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            reqTransport_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RouteSelection.RouteSelectionImpl.internal_static_RouteSelection_requestTransport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RouteSelection.RouteSelectionImpl.internal_static_RouteSelection_requestTransport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RouteSelection.requestTransport.class, RouteSelection.requestTransport.Builder.class);
  }

  public static final int REQTRANSPORT_FIELD_NUMBER = 1;
  private volatile java.lang.Object reqTransport_;
  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string reqTransport = 1;</code>
   */
  public java.lang.String getReqTransport() {
    java.lang.Object ref = reqTransport_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reqTransport_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string reqTransport = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReqTransportBytes() {
    java.lang.Object ref = reqTransport_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reqTransport_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReqTransportBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqTransport_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReqTransportBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqTransport_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RouteSelection.requestTransport)) {
      return super.equals(obj);
    }
    RouteSelection.requestTransport other = (RouteSelection.requestTransport) obj;

    boolean result = true;
    result = result && getReqTransport()
        .equals(other.getReqTransport());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQTRANSPORT_FIELD_NUMBER;
    hash = (53 * hash) + getReqTransport().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RouteSelection.requestTransport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RouteSelection.requestTransport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RouteSelection.requestTransport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RouteSelection.requestTransport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RouteSelection.requestTransport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RouteSelection.requestTransport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RouteSelection.requestTransport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RouteSelection.requestTransport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RouteSelection.requestTransport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RouteSelection.requestTransport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RouteSelection.requestTransport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RouteSelection.requestTransport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RouteSelection.requestTransport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RPC message Method 2
   * </pre>
   *
   * Protobuf type {@code RouteSelection.requestTransport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RouteSelection.requestTransport)
      RouteSelection.requestTransportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RouteSelection.RouteSelectionImpl.internal_static_RouteSelection_requestTransport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RouteSelection.RouteSelectionImpl.internal_static_RouteSelection_requestTransport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RouteSelection.requestTransport.class, RouteSelection.requestTransport.Builder.class);
    }

    // Construct using RouteSelection.requestTransport.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reqTransport_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RouteSelection.RouteSelectionImpl.internal_static_RouteSelection_requestTransport_descriptor;
    }

    @java.lang.Override
    public RouteSelection.requestTransport getDefaultInstanceForType() {
      return RouteSelection.requestTransport.getDefaultInstance();
    }

    @java.lang.Override
    public RouteSelection.requestTransport build() {
      RouteSelection.requestTransport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public RouteSelection.requestTransport buildPartial() {
      RouteSelection.requestTransport result = new RouteSelection.requestTransport(this);
      result.reqTransport_ = reqTransport_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RouteSelection.requestTransport) {
        return mergeFrom((RouteSelection.requestTransport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RouteSelection.requestTransport other) {
      if (other == RouteSelection.requestTransport.getDefaultInstance()) return this;
      if (!other.getReqTransport().isEmpty()) {
        reqTransport_ = other.reqTransport_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RouteSelection.requestTransport parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RouteSelection.requestTransport) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object reqTransport_ = "";
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string reqTransport = 1;</code>
     */
    public java.lang.String getReqTransport() {
      java.lang.Object ref = reqTransport_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqTransport_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string reqTransport = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqTransportBytes() {
      java.lang.Object ref = reqTransport_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqTransport_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string reqTransport = 1;</code>
     */
    public Builder setReqTransport(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reqTransport_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string reqTransport = 1;</code>
     */
    public Builder clearReqTransport() {
      
      reqTransport_ = getDefaultInstance().getReqTransport();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *client digita endereco
     * </pre>
     *
     * <code>string reqTransport = 1;</code>
     */
    public Builder setReqTransportBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reqTransport_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RouteSelection.requestTransport)
  }

  // @@protoc_insertion_point(class_scope:RouteSelection.requestTransport)
  private static final RouteSelection.requestTransport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RouteSelection.requestTransport();
  }

  public static RouteSelection.requestTransport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<requestTransport>
      PARSER = new com.google.protobuf.AbstractParser<requestTransport>() {
    @java.lang.Override
    public requestTransport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new requestTransport(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<requestTransport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<requestTransport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public RouteSelection.requestTransport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

