// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteSelection.proto

package RouteSelection;

public interface requestTransportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RouteSelection.requestTransport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string reqTransport = 1;</code>
   */
  java.lang.String getReqTransport();
  /**
   * <pre>
   *client digita endereco
   * </pre>
   *
   * <code>string reqTransport = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqTransportBytes();
}
