// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteSelection.proto

package RouteSelection;

public interface routeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RouteSelection.route)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *select the route
   * </pre>
   *
   * <code>string stringAddress = 1;</code>
   */
  java.lang.String getStringAddress();
  /**
   * <pre>
   *select the route
   * </pre>
   *
   * <code>string stringAddress = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringAddressBytes();
}
