// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteSelection.proto

package RouteSelection;

public interface routeSelectedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RouteSelection.routeSelected)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *sistema entendera que a string representa a procura do endereco
   * </pre>
   *
   * <code>string destination = 1;</code>
   */
  java.lang.String getDestination();
  /**
   * <pre>
   *sistema entendera que a string representa a procura do endereco
   * </pre>
   *
   * <code>string destination = 1;</code>
   */
  com.google.protobuf.ByteString
      getDestinationBytes();
}
