// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RouteSelection.proto

package RouteSelection;

public interface transportAvailableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RouteSelection.transportAvailable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *sistema devolve a distacia ate o destino
   * </pre>
   *
   * <code>string kindTransport = 1;</code>
   */
  java.lang.String getKindTransport();
  /**
   * <pre>
   *sistema devolve a distacia ate o destino
   * </pre>
   *
   * <code>string kindTransport = 1;</code>
   */
  com.google.protobuf.ByteString
      getKindTransportBytes();
}
